joint1_position:
  type: position_controllers/JointPositionController
  joint: joint1

joint2_position:
  type: position_controllers/JointPositionController
  joint: joint2

joint3_position:
  type: position_controllers/JointPositionController
  joint: joint3

joint4_position:
  type: position_controllers/JointPositionController
  joint: joint4

gazebo_ros_control:
  pid_gains:
    joint1:
      p: 600
      i: 60
      d: 6
    joint2:
      p: 1000
      i: 1
      d: 0.1
    joint3:
      p: 500
      i: 50
      d: 5
    joint4:
      p: 300
      i: 30
      d: 3
    